DMTF/python-redfish-library

src/redfish/rest/v1.py
def _rest_request(...) is appending a trailing slash to all URIs:
if self.default_prefix in path and path[-1] != '/':
path = path + '/'
else:
pass
but my read of the spec says that only needed for the root of the namespace '/redfish/v1/'. Change is to only append when default does not contain a trailing '/'.
=> avoid _rest_request appending '/' to all URIs

src/redfish/rest/v1.py
Add enter/exit methods to RestClient base to handle login/logout
when using `with RestClientBase() as d:` syntax
=> Add context manager to RestClientBase

src/redfish/rest/v1.py
headers need to be in dict otherwise they are not used (only tested for patch though)
=> Fix type for headers

src/redfish/rest/v1.py
For issue #22. The original code for handling gzip content type was treating the binary gzipped data as text (string). Updated code to handle the gzip data as bytes and then the unzipped data as a string.
Fixes #22
=> Treat gzip data as bytes; unzipped data as string

README.rst, src/redfish/rest/v1.py
The use of `Content-Type: application/x-www-form-urlencoded` is not appropriate for Redfish POST/PATCH/PUT.
Removed the existing code that was doing that and replaced it with a warning.
If a POST, PATCH, or PUT is issued with _both_ an `args=` param and a `body=` param, a warning is issued that indicates the `args=` param is ignored:
> For POST, PUT and PATCH methods, the provided "args" parameter "{'ResetType': 'GracefulShutdown'}" is ignored.
If a POST, PATCH, or PUT is issued with _only_ an `args=` param, a warning is issued that indicates the `args=` param is ignored and that the `body=` param should be used:
> For POST, PUT and PATCH methods, the provided "args" parameter "{'ResetType': 'GracefulShutdown'}" is ignored.
> Use the "body" parameter to supply the request payload.
Fixes …
=> Correct incorrect use of x-www-form-urlencoded for POST/PATCH/PUT

README.rst, src/redfish/rest/v1.py
#29 
Added an optional timeout argument for the initial connection, in seconds. Removed the hardcoded MAX_RETRY attribute and added an optional max_retry argument for the amount of times a request will retry after a timeout. Changed attempts and max_retry evaluation so it may work with a max_retry value of 1
=> Added optional timeout and max_retry args

README.rst, src/redfish/rest/v1.py
Sample code to run against
```
import redfish
context = redfish.redfish_client('https://192.168.1.254', '...', '...')
context.login()
payload = context.post(
'/redfish/v1/Systems/System.Embedded.1/Storage/Volumes/.../Actions/Volume.CheckConsistency', body={})
print("Status:", payload.status)
print("Processing?: ", payload.is_processing)
count = 0
if (payload.is_processing):
while(payload.is_processing):
count+=1
print("Tries:", count)
payload = payload.process_task(context)
print("Status:", payload.status)
print("Processing?: ", payload.is_processing)
else:
pass
print(payload)
```
=> Added functions for handling Tasks easier

tests/ris/test_config.py, tests/ris/test_ris.py
In python 2.7 to create tmp dir we need to use [`mkdtemp`](https://docs.python.org/2/library/tempfile.html#tempfile.mkdtemp) so fixing the issue and now unit test works well with py27 and py3+
Also applying pep8 on tests too
=> Fix an issue with unit test on config file and py27 and the tempfile module

src/redfish/rest/v1.py
The library has logic to retry REST requests when exceptions are raised. If max retries are attempted a `RetriesExhaustedError` is raised. But the original exception is lost. So the user only sees the `RetriesExhaustedError` and has no idea what the actual cause is (e.g. a `ConnectionRefusedError`). We have seen several Github issues opened by users that have encountered this.
The PR adds the original exception so that it is displayed before the RetriesExhaustedError.
**Before** output:
```
Traceback (most recent call last):
File "examples/quickstart.py", line 18, in <module>
password=login_password, default_prefix='/redfish/v1')
File "./python-redfish-library/src/redfish/rest/v1.py", line 1059, in redfish_client
max_retry=max_retry)
File "./python-redfish-library/src/redfish/rest/v1.py", …
```
=> Include original exception when raising RetriesExhaustedError

src/redfish/rest/v1.py
Strip any trailing slashes from `base_url`. For example:
"https://192.168.1.20/" -> "https://192.168.1.20"
This fixes a problem during logout when the base_url is removed from the absolute session URL, resulting in the session URL being transformed from:
`https://192.168.1.20/redfish/v1/SessionService/Sessions/<session_id>`
to:
`redfish/v1/SessionService/Sessions/<session_id>` (note the missing leading slash)
Fixes #57
=> Strip any trailing slashes from base_url

src/redfish/rest/v1.py
When trying to connect to a Huawei TaiShan server the connect would throw an "KeyError" exception. Huawai didn't implement the "Links" Key. And It shouldn't be assumed the Key to be present.
Here is a example of a Huawei root service:
```
{
"@odata.context": "/redfish/v1/$metadata#ServiceRoot",
"@odata.id": "/redfish/v1/",
"@odata.type": "#ServiceRoot.v1_1_0.ServiceRoot",
"AccountService": {
"@odata.id": "/redfish/v1/AccountService"
},
"Chassis": {
"@odata.id": "/redfish/v1/Chassis"
},
"EventService": {
"@odata.id": "/redfish/v1/EventService"
},
"Id": "RootService",
"JsonSchemas": {
"@odata.id": "/redfish/v1/JSONSchemas"
},
"Managers": {
"@odata.id": "/redfish/v1/Managers"
},
"Name": "Root Service",
"Oem": {
"Huawei": {
"AccountLockoutDuration": 300,
"Copyright": "Huawei Technologies Co., …
```
=> check if SessionService Link key is present in redfish root data

src/redfish/rest/v1.py, src/redfish/ris/rmc.py
=> Changed calls to time.clock to use time.perf_counter when Python is older than 3.3

requirements.txt, setup.py, src/redfish/ris/rmc_helper.py, tests/ris/test_rmc_helper.py, tox.ini
Made the following updates:
- removed urlparse2 dependency
- added unit test for impacted method
- updated jsonpatch requirements spec (jsonpatch 1.25 dropped Python 3.4 support)
Fixes #78
=> Remove urlparse2 dependency

.gitignore, README.rst, src/redfish/rest/v1.py
Add proxy support via the HTTP_PROXY and HTTPS_PROXY environment variables, similar to the support in urllib.
=> Add proxy support via environment variables

tox.ini
- Update tox `testtools` prereq for the py34 environment
- Add py38 to the tox environment list
Fixes #85
=> tox: add py38 and update testtools prereq for py34

.travis.yml
Added Python 3.8 to the Travis-CI config (.travis.yml). I added both the stable and dev build for 3.8. But I removed the dev builds for 3.5 and 3.6 as those should be quite stable these days.
=> Add python 3.8 to travis config

src/redfish/discovery/discovery.py
In case interface has multiple IP addresses,
discovery will not work correctly
So adding new option to bind to specific address
if provided as an argument
=> Add binding address to discover_ssdp

src/redfish/rest/v1.py
When base URL scheme is HTTP, logout will fail as below:
```
>>> from redfish import redfish_client
>>> with redfish_client('https://10.30.170.53','',''): pass
... 
>>> with redfish_client('http://10.30.170.53','',''): pass
... 
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/tmp/python-redfish-library/src/redfish/rest/v1.py", line 532, in __exit__
self.logout()
File "/tmp/python-redfish-library/src/redfish/rest/v1.py", line 987, in logout
"return code: %d" % (session_loc, resp.status))
redfish.rest.v1.BadRequestError: Invalid session resource: https://10.30.170.53/redfish/v1/SessionService/Sessions/%5bnone%5d000000005f22dae6170a3d71/, return code: 405
```
The root cause is that the scheme of `self.__base_url` is still HTTP rather than HTTPS the Redfish API …
=> Fix logout failure while base URL scheme is HTTP

src/redfish/rest/v1.py
As in subject, these headers 
Test script
```
import redfish
REDFISH_OBJ = redfish.redfish_client(
base_url='https://10.172.201.217',
username='admin', password='admin',
default_prefix='/redfish/v1')
REDFISH_OBJ.login()
iheaders = {'Accept': 'application/xml'}
response = REDFISH_OBJ.get('/redfish/v1/Managers', headers=iheaders)
print (f"Request with Accept header set to application/xml: status {response.status}")
response = REDFISH_OBJ.get('/redfish/v1/Managers')
print (f"Request without defined headers: status {response.status}")
iheaders = {'OData-Version': '5.0'}
response = REDFISH_OBJ.get('/redfish/v1/Managers', headers=iheaders)
print (f"Request with OData-Version header set to 5.0: status {response.status}")
iheaders = {'Accept': 'application/json'}
response = …
```
=> Make HTTP headers Accept and OData-Version configurable for user

src/redfish/rest/v1.py
With a `303 See Other` redirect, must use the GET method on the new URI. Update the redirect handling code to account for this case.
Fixed #98
=> Fix redirect handling for 303 See Other

.travis.yml, tox.ini
Also, remove 3.8-dev from .travis.yml since the regular released 3.8 is already specified.
Fixes #103
=> Add py39 to tox and travis configs

requirements.txt, setup.py, src/redfish/rest/v1.py
Looking to simplify the library by leveraging requests instead of http.client since requests has functionality we're currently duplicating in this library.
Need more eyes on this to see how this integrates with existing tools.
There are more things I'd like to remove since some of the internal helper classes seem to duplicate data in several places, but the current changes address the bulk of the heavy lifting we've done prior that are handled internally with requests.
=> Converting the library to use requests

src/redfish/rest/v1.py
if you need to use default_prefix='/redfish/v1'
instead of default_prefix='/redfish/v1/' this block of code prevents it from doing so.
=> fix use default_prefix

README.rst, src/redfish/rest/v1.py, src/redfish/ris/rmc.py, src/redfish/ris/rmc_helper.py
Leverages `proxies` parameter in the requests module so that environment variables are not required to use proxies.
Signed-off-by: Mike Raineri <michael.raineri@dell.com>
=> Added methods for specifying proxies directly

src/redfish/rest/v1.py
From the RFC, the query string follows this definition: `*( pchar / "/" / "?" )`
pchar is defined as: `unreserved / pct-encoded / sub-delims / ":" / "@"`
unreserved is defined as: `ALPHA / DIGIT / "-" / "." / "_" / "~"`
sub-delims is defined as `"!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="`
So, characters like $ (and others used in Redfish) do not need to be percent-encoded per the RFC.
=> Modified query parameter encoding to not percent-encode characters allowed in query strings per RFC3986

src/redfish/rest/v1.py
=> Added handling for extracting error information when a session could not be created

src/redfish/discovery/discovery.py
Fix #142 
@PeterKchen2 would you be able to test this on your system for me? I don't have access to an AMI system and other systems are able to handle the missing newline in the request.
=> Added missing new line in M-SEARCH request

src/redfish/__init__.py, src/redfish/messages/__init__.py, src/redfish/messages/messages.py, src/redfish/rest/v1.py
PasswordChangeRequired support
=> PasswordChangeRequired support

src/redfish/discovery/discovery.py, src/redfish/messages/messages.py, src/redfish/rest/v1.py
Python 3.12 introduced a SyntaxWarning for invalid escape sequences in string literals. Use raw string literals where strings with backslash characters are required.
=> Fix syntax warnings with Python 3.12

.travis.yml, src/redfish/rest/v1.py, tox.ini
=> Removed clearing of username and password to allow for sessions to be re-established

README.rst, src/redfish/rest/v1.py, tests/rest/test_v1.py
This allows a user to create a client without _knowing_ the IP they are connecting to up front. It gives the user the ability to create and pass around a client object as needed. Additionally, the default behavior is preserved.
* Added `check_connectivity` keyword arg to `RestClientBase`.
* Added `check_connectivity` keyword arg to `HTTPClient`.
* Added `check_connectivity` keyword arg to `redfish_client` function.
* Conditionally execute `get_root_object` during client instantiation based on the value of `check_connectivity`.
* Catch the resultant `AttributeError` in the case that `self.root` was not set due to `check_connectivity` being set to `False`.
* Small test refactor, added `setUp` method to `TestRedFishClient` class to make commonly used attributes members of the test case.
* …
=> Issue #163: Optional Connection upon Client Instantiation

src/redfish/rest/v1.py
Fix #165 
@v-ajitpanda FYI you may want to test this on your end before we merge this. I've stood up a system that returns 401 and it works well on my end.
=> Added workaround for services incorrectly responding with 401 when accessing the service root

src/redfish/rest/v1.py
=> Updated 'dict' handling for responses without a body to use an empty dictionary

src/redfish/rest/v1.py
A generic change allowing to set arbitrary headers on the login request, which is already supported by, e.g., `get`, `head`, and `post`.
In my case, I want to access a RedFish endpoint, which is only reachable using local port forwarding. In such a situation, the authentication requests leads to a `Base.1.12.AccessDenied`. Presumably because the request is for `localhost:<forward port>` instead of `<bmc ip>:<bmc port>`. This can be resolved by setting the `Host` HTTP header to `<bmc ip>`, which I can easily do with the proposed change.
=> Add possibility to provide headers for login requests

src/redfish/rest/v1.py
I had some folks who were looking at the existing message in the "ServerDownOrUnreachableError" exception and were interpreting it as a network issue when in fact it's just a bad response from the service. Made adjustments to indicate the service is responsive (but just not in a satisfactory way).
=> Clarified the exception message raised when unable to access the service root

src/redfish/rest/v1.py
Fix #172 
After discussing this with others in the forum, we think it's beneficial to automate a workaround (and print warnings about the non-conformance). The Redfish-Protocol-Validator already flags this as an error, so vendors can test for it today.
=> Added workaround and warnings for session login when the service incorrectly does not provide the session location in the 'Location' response header

src/redfish/rest/v1.py
Fixed bug in recent workaround logic for services not returning the 'Location' header to not print the workaround warning for failed login attempts
Failed login attempts are expected to not return a Location header.
=> Fixed bug in recent workaround logic for services not returning the 'Location' header
