CHANGELOG.md, README.rst, makeandinstallzip.bat, setup.py, src/redfish/rest/v1.py, src/redfish/ris/__init__.py, src/redfish/ris/config.py, src/redfish/ris/ris.py, src/redfish/ris/rmc.py, src/redfish/ris/rmc_helper.py
=> Python 3 compatibility

src/redfish/rest/v1.py
The way the original Python 2 code was getting the response headers in some debug logging code didn't port to Python 3. Changed the way it was getting the headers to be more portable.
(Used `restresp.getheaders()` instead of `restresp._http_response.msg.headers`)
Also fixed a few other errors and warnings in src/redfish/rest/v1.py flagged by my IDE.
Fixes #6
=> Fix the way debug code was getting headers to be more portable

README.rst
Updated the pip install command
Updated the image widgets to work with the new pypi project
=> Updated readme for pypi project

src/redfish/rest/v1.py
Changes:
- Add exception BadRequestError() class.
- Add HTTP request response check in logout().
Tested:  OpenBMC redfish.
Resolves  DMTF/python-redfish-library#14
=> Handle bad or dummy delete request in logout()

src/redfish/rest/v1.py
Updates:
- Fixed success status checking to allow for appropriate success codes
- Fixes a message substitution error
Fixes #17
=> check appropriate success status codes and fix error formatting

src/redfish/rest/v1.py
This PR is to add new parameters to Redfish Client for SSL verification.
=> Parameterize SSL verification in the Client

.travis.yml, tox.ini
Implement a fresh testing environment to receive unit tests,
checker etc... in the future.
These changes start to run unit tests but no unit test was implemented
for now, so we just need to continue by implementing these tests in a
second time.
=> Introduce base environment for testing purpose

tests/test_redfish.py
Introduce some tests on:
- redfish_client
- HttpClient
=> Introduce unittests on rest v1

src/redfish/discovery/__init__.py, src/redfish/discovery/discovery.py, tests/discovery/test_discovery.py, tests/rest/test_v1.py, tox.ini
My changes are composed of 2 commits:
- 1 commit to introduce new unit tests on the `src/redfish/discovery` module and refactor the tested module by applying pep8 rules.
- 1 commit to introduce check with tox and flake8
I don't activate flake8 checks on the whole project to avoid tons of pep8 errors. I prefer isolate pep8 changes module per module to simplify refactor by doing it step by step.
=> Introduce unit tests on src/redfish/discovery

src/redfish/ris/config.py, src/redfish/ris/ris.py, tests/ris/test_config.py, tests/ris/test_ris.py
Changes:
- Adding some unittests on the ris module
- Applying PEP8 on the ris module
=> Introduce unit tests on ris and apply PEP8 on ris

examples/context_manager.py, src/redfish/rest/v1.py
Fix #54: Changed default login method to use sessions
Fix #46: Removed unnecessary closing of sockets on each request
=> Performance enhancements

src/redfish/discovery/discovery.py
Fix #58
@mraineri please review
=> Add binding interface to discover_ssdp

src/redfish/rest/v1.py
=> Inspect HTTPSConnection to see if context arg is supported

src/redfish/ris/ris.py
Per discussion during the Tools TF call on 10/3/2019, created this PR to better address the robustness of the monolith building in `RisMonolith_v1_0_0._load()`. Added exception handling around the URL parsing and GET requests in the recursive monolith building method. If an exception is caught, a message is displayed, that resource is skipped, and the monolith building continues.
**Before fix:**
```
$ python3 redfish-uri-validator.py --user "" --password "" --rhost http://127.0.0.1:8007 --openapi ~/Development/DMTF/Schemas/DSP8010_2019.1/openapi/openapi.yaml 
Opening ~/Development/DMTF/Schemas/DSP8010_2019.1/openapi/openapi.yaml...
Config file '/etc/redfish/redfish.conf' not found
Service URI: http://127.0.0.1:8007
Logging in and downloading resources; this may take a while...
ERROR: …
```
=> Add exception handling in RisMonolith_v1_0_0._load()

README.rst, src/redfish/rest/v1.py
=> Add NO_PROXY environment variable support

.travis.yml, README.rst, examples/context_manager.py, examples/discover.py, examples/quickstart.py, examples/quickstart_rmc.py, requirements.txt, setup.py, src/redfish/__init__.py, src/redfish/discovery/__init__.py, src/redfish/discovery/discovery.py, src/redfish/rest/__init__.py, src/redfish/rest/v1.py, src/redfish/ris/__init__.py, src/redfish/ris/config.py, src/redfish/ris/ris.py, src/redfish/ris/rmc.py, src/redfish/ris/rmc_helper.py, src/redfish/ris/sharedtypes.py, tests/__init__.py, tests/discovery/__init__.py, tests/discovery/test_discovery.py, tests/rest/__init__.py, tests/rest/test_v1.py, tests/ris/__init__.py, tests/ris/test_config.py, tests/ris/test_ris.py, tests/ris/test_rmc_helper.py, tox.ini
Removed Python2 support; this also removes the usage of the six module.
At the same time, I cleaned up various trivial warnings my IDE was throwing (such as superfluous usage of backslashes).
Fix #104 
Fix #101
=> Removed Python2 support

src/redfish/rest/v1.py
=> Modified redirect handling to turn into GET for HTTP status codes 301 and 302

src/redfish/rest/v1.py
Added handling of invalid JSON in responses to make it clear that the exception is caused by the service
=> Improved invalid JSON response handling

README.rst
=> Various README clarifications

requirements.txt, setup.py, src/redfish/rest/v1.py
Proposal for adding Unix socket support.
Fix #120
=> Added Unix sockets

src/redfish/rest/v1.py
Fix #125 
I looked further at the history of some of the response methods, and this is what I can gather:
* `read` returns raw contents (as bytes)
* `text` returns the response as a string
* `dict` returns the response as a dictionary
When converting to use `requests`, `read` was erroneously changed to always return a string. However, one thing worth noting is if someone is using the mechanisms in place to set data in the response object, `read` will be converted to a string. We should look at this further to ensure consistency, but that might break usage for others. The functionality we have in this PR is equivalent to what we had prior to moving to `requests`.
=> Fixed issue where the 'read' method on response objects always return strings

README.rst
=> Updated readme to document SOCKS proxy usage

src/redfish/rest/v1.py
* Added request headers to debug log output
* Added redacting of 'Password' properties from request bodies from debug logs
=> Debug logging enhancements

.github/workflows/main.yml, README.rst, examples/context_manager.py, examples/discover.py, examples/multipart_push.py, examples/quickstart.py, examples/quickstart_rmc.py, setup.py, src/redfish/__init__.py, src/redfish/discovery/__init__.py, src/redfish/discovery/discovery.py, src/redfish/rest/__init__.py, src/redfish/rest/v1.py, src/redfish/ris/__init__.py, src/redfish/ris/config.py, src/redfish/ris/ris.py, src/redfish/ris/rmc.py, src/redfish/ris/rmc_helper.py, src/redfish/ris/sharedtypes.py, tests/__init__.py, tests/discovery/__init__.py, tests/discovery/test_discovery.py, tests/rest/__init__.py, tests/rest/test_v1.py, tests/ris/__init__.py, tests/ris/test_config.py, tests/ris/test_ris.py, tests/ris/test_rmc_helper.py
Fix #140 
Will refine based on feedback; more work needed to add to the README.
=> Documentation updates for clarity

README.rst, src/redfish/rest/v1.py
all redfish method have timeout and max_retry options 
Fix #136
=> all redfish method have timeout and max_retry options

README.rst
=> Updated README to include requirements called out in requirements.txt

README.rst
User emailed me about this discrepancy...
=> Corrected variable names in sample code for task handling

src/redfish/rest/v1.py
Based on [Issue#167](https://github.com/DMTF/python-redfish-library/issues/167), here are the changes.
=> change the rest resp as json format
